apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homelab-pg

resources:
# - init-hyperatbles-configmap.yaml
# - init-db-clientes-configmap.yaml
- vault/sa.yaml
- vault/vault-auth.yaml
- vault/vault-secs.yaml
- users.yaml
- cluster.yaml
- poolers.yaml
- init-db-configmap.yaml
- backup.yaml
- objectStoreCeph.yaml
- databases.yaml