envFrom:
  - secretRef:
      name: oauth2-secrets

replicaCount: 2
proxyVarsAsSecrets: false
# ingress:
#   enabled: true
#   ingressClassName: traefik
#   hosts:
#     - oauth2.famcr.org
#   tls:
#     - secretName: oauth2-certificate-secret
#       hosts:
#         - oauth2.famcr.org

sessionStorage:
  type: redis
  redis:
    sentinel:
      existingSecret: oauth2-redis-auth
      passwordKey: "redis-password"
      masterName: "homelabredis"
      connectionUrls:
        - "redis://redis-node-0.redis-headless.redis.svc.cluster.local:26379"
        - "redis://redis-node-1.redis-headless.redis.svc.cluster.local:26379"
        - "redis://redis-node-2.redis-headless.redis.svc.cluster.local:26379"
    clientType: sentinel
redis:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
