---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bike-mcp-ingressroute-certificate
  namespace: bike-mcp
spec:
  secretName: bike-mcp-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - bike-mcp.famcr.org
