---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onvo-mcp-ingressroute-certificate # <-- Replace with your certificate name
  namespace: onvo-mcp # <-- Replace with your namespace
spec:
  secretName: onvo-mcp-certificate-secret # <-- Replace with your secret name
  issuerRef:
    name: cloudflare-clusterissuer # <-- Replace with your issuer name
    kind: ClusterIssuer
  dnsNames:
    - onvo-mcp.famcr.org # <-- Replace with your hostname
