---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-ingressroute-certificate # <-- Replace with your certificate name
  namespace: openbao  # <-- Replace with your namespace
spec:
  secretName: openbao-certificate-secret  # <-- Replace with your secret name
  issuerRef:
    name: cloudflare-clusterissuer  # <-- Replace with your issuer name
    kind: ClusterIssuer
  dnsNames:
    - openbao.famcr.org  # <-- Replace with your hostname