---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox-ingressroute-certificate # <-- Replace with your certificate name
  namespace: default  # <-- Replace with your namespace
spec:
  secretName: proxmox-certificate-secret  # <-- Replace with your secret name
  issuerRef:
    name: cloudflare-clusterissuer  # <-- Replace with your issuer name
    kind: ClusterIssuer
  dnsNames:
    - proxmox.famcr.org  # <-- Replace with your hostname