---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-ingressroute-certificate # <-- Replace with your certificate name
  namespace: arrstack # <-- Replace with your namespace
spec:
  secretName: qbittorrent-certificate-secret # <-- Replace with your secret name
  issuerRef:
    name: cloudflare-clusterissuer # <-- Replace with your issuer name
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.famcr.org # <-- Replace with your hostname
