---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: technitium-ingressroute-certificate # <-- Replace with your certificate name
  namespace: technitium # <-- Replace with your namespace
spec:
  secretName: technitium-certificate-secret # <-- Replace with your secret name
  issuerRef:
    name: cloudflare-clusterissuer # <-- Replace with your issuer name
    kind: ClusterIssuer
  dnsNames:
    - technitium.famcr.org # <-- Replace with your hostname
