apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-config
  namespace: monitoring
data:
  oidc-grafana.ini: |
    [auth.generic_oauth]
    enabled = true
    name = Keycloak-OAuth
    allow_sign_up = true
    client_id = grafana
    client_secret = REDACTED_SECRET
    scopes = openid email profile offline_access roles
    email_attribute_path = email
    login_attribute_path = username
    name_attribute_path = full_name
    auth_url = https://keycloak.famcr.org/realms/master/protocol/openid-connect/auth
    token_url = https://keycloak.famcr.org/realms/master/protocol/openid-connect/token
    api_url = https://keycloak.famcr.org/realms/master/protocol/openid-connect/userinfo
    role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'