# dnsmasq:
#   customDnsEntries:
#     - address=/pihole.famcr.org/100.91.10.38
#   additionalHostsEntries:
#     - 100.91.10.38    longhorn.famcr.org     longhorn
#     # - 100.91.10.38    pihole.famcr.org     pihole
#     - 100.91.10.38    proxmox.famcr.org     proxmox
#     - 100.91.10.38    vault.famcr.org     vault
#     - 100.91.10.38    keycloak.famcr.org     keycloak
#     - 100.91.10.38    grafana.famcr.org     grafana
#     - 100.91.10.38    prometheus.famcr.org     prometheus
dnsmasq:
  enableCustomDnsMasq: false
# dnsmasq:
#   upstreamServers: 
#     - 127.0.0.1#5335   # ensure this is empty

serviceWeb:
  type: ClusterIP
  port: 80

monitoring:
  podMonitor:
    enabled: true
  sidecar:
    enabled: true
doh:
  enabled: true
  # monitoring:
  #   podMonitor:
  #     enabled: true

extraEnvVars:
  TZ: "America/Costa_Rica"
  # FTLCONF_dns_upstreams: '10.43.219.49#5335'

  
serviceDns:
  mixedService: true
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerClass: "tailscale"
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: pihole-dns
    # tailscale.com/tags: 'tag:ingress-web'
    # metallb.universe.tf/address-pool: default   # if you use MetalLB
  # port: 53
  # protocol: UDP

DNS1: "1.1.1.1"
DNS2: "8.8.8.8"

nebulaSync:
  enabled: true
  password: ''

  
admin:
  enabled: false

replicaCount: 2
# Optional: set a static web password env var if desired

# Create this ConfigMap separately (example below)

# ingress:
#   enabled: true
#   className: "traefik"
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#   hosts:
#     - pihole.famcr.org
#   tls:
#     - secretName: pihole-certificate-secret
#       hosts:
#         - pihole.famcr.org

persistentVolumeClaim:
  enabled: true