apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - vault/sa.yaml
  - vault/vault-auth.yaml
  - vault/vault-dynamic-secret.yaml
  - operator/
  # - keycloak-initial-admin-secret.yaml
  - keycloak-cr.yaml
