apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onvo-mcp

resources:
  - sa.yaml
  - vault-auth.yaml
  - vault-secs.yaml
  - deployment.yaml
  - service.yaml
# - ingress-route.yaml
