ingress:
  enabled: true
  hosts:
    - host: technitium.famcr.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - technitium.famcr.org
      secretName: technitium-certificate-secret

replicaCount: 3
clustering:
  # -- Enable clustering support (automatically configures per-pod domain names,
  # HTTPS with self-signed certs, and pod anti-affinity)
  enabled: true
  # -- Use pod anti-af
