ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: technitium.famcr.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - technitium.famcr.org
      secretName: technitium-certificate-secret
serviceDns:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies

serviceDoh:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies

replicaCount: 2
clustering:
  enabled: true
  hostNetwork: false
