ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: technitium.famcr.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - technitium.famcr.org
      secretName: technitium-certificate-secret
serviceDns:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: technitium-dns

serviceDoh:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: technitium-doh

replicaCount: 1
clustering:
  enabled: false
  hostNetwork: false

# Pin pods to nodes labeled with technitium-dns=true
# Label 3 nodes: kubectl label node <name> technitium-dns=true
nodeSelector:
  technitium-dns: "true"
