---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: monitoring
  name: vault-auth
spec:
  vaultAuthGlobalRef:
    namespace: hashicorp
    allowDefault: true
  kubernetes:
    audiences:
      - https://kubernetes.default.svc
    role: grafana
