---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: monitoring
  name: vault-auth
spec:
  # kubernetes:
  #   role: vault-apps
  #   serviceAccount: vault-sa
  vaultAuthGlobalRef:
    namespace: hashicorp
    allowDefault: true
  kubernetes:
    role: grafana
