jellyfin:
  enabled: false

sonarr:
  enabled: false

radarr:
  enabled: false

prowlarr:
  enabled: false

qbittorrent:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: qbittorrent.famcr.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: qbittorrent-certificate-secret
        hosts:
          - qbittorrent.famcr.org

flaresolverr:
  enabled: false

jellyseerr:
  enabled: false

bazarr:
  enabled: false

cleanuparr:
  enabled: false

lidarr:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: lidarr.famcr.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: lidarr-certificate-secret
        hosts:
          - lidarr.famcr.org
