apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: networking

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  # Multiple sources combined
  sources:
    # 1) Traefik Helm chart from Helm repo
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.3.0      # <- set this to the chart version you used
      helm:
        valueFiles:
          - $values/traefik/values.yaml   # values.yaml from your repo

    # 2) Your repo with extra manifests + the values file
    - repoURL: https://github.com/jcampos2907/homelab.git
      targetRevision: main
      ref: values
      path: traefik
      directory:
        recurse: true
        exclude: "{excluded/**}"

  # Start manual so nothing is changed until you click Sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
