# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: kube-system

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
#   - name: coredns-custom
#     files:
#       - custom/00-forward.override

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - custom/coredns-configmap-patch.yaml
  - coredns-restart-rbac.yaml
  - coredns-restart-job.yaml
